language: python

python: 
    - "2.7"
    - "3.4"
    - "3.5"

install:
    - pip install -r requirements-test.txt
    - pip install coveralls
    - pip install flake8

before_script:
    - flake8 --max-line-length=100 .

script:
    - py.test

after_success:
    - coveralls
